# Generated by Django 6.1.1 on 2026-09-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Short summary displayed on event cards.')),
                ('description', models.TextField(blank=True, help_text='Full description of the event.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, help_text='Example: Etinan LGA, Akwa Ibom State', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('registration_open', models.BooleanField(default=False, help_text='Enable registration for this event.')),
                ('registration_url', models.URLField(blank=True, help_text='Optional external registration link.')),
                ('featured', models.BooleanField(default=False, help_text='Featured events receive prominent placement.')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Event',
                'verbose_name_plural': 'Campaign Events',
                'ordering': ['event_date', 'start_time', '-created_at'],
            },
        ),
    ]
