# Generated by Django 6.1.1 on 2026-09-11 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('volunteer', models.BooleanField(default=False, help_text='Supporter is interested in volunteering.')),
                ('skills', models.TextField(blank=True, help_text='Optional skills or areas where the supporter can contribute.')),
                ('receive_updates', models.BooleanField(default=True, help_text='Supporter agrees to receive campaign updates.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('contacted', 'Contacted'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal administrative notes.')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supporter',
                'verbose_name_plural': 'Supporters',
                'ordering': ['-registered_at'],
            },
        ),
    ]
