# Generated by Django 6.1.1 on 2026-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default='Hon. Emem Jackson', max_length=150)),
                ('position', models.CharField(blank=True, help_text='Example: Candidate for Federal House of Representatives', max_length=200)),
                ('campaign_name', models.CharField(default='UDUAK-ABASI 2027', max_length=150)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.TextField(blank=True, help_text='Short biography used on the homepage.')),
                ('biography', models.TextField(blank=True, help_text='Full biography used on the About page.')),
                ('vision', models.TextField(blank=True, help_text='Campaign vision statement.')),
                ('mission', models.TextField(blank=True, help_text='Campaign mission statement.')),
                ('hero_image', models.ImageField(blank=True, help_text='Main image used in the homepage hero section.', null=True, upload_to='campaign/')),
                ('profile_image', models.ImageField(blank=True, help_text='Candidate profile image.', null=True, upload_to='campaign/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X')),
                ('youtube', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active campaign profile will be displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Profile',
                'verbose_name_plural': 'Campaign Profile',
                'ordering': ['-updated_at'],
            },
        ),
    ]
