# Generated by Django 6.1.1 on 2026-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, help_text='Display order of this agenda item.')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short description of this agenda item.')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class, e.g. fa-solid fa-briefcase', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only active agenda items will appear on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agenda Item',
                'verbose_name_plural': 'Agenda Items',
                'ordering': ['number', 'title'],
            },
        ),
    ]
