# Generated by Django 6.1.1 on 2026-09-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('interest', models.CharField(choices=[('volunteering', 'General Volunteering'), ('community', 'Community Mobilisation'), ('youth', 'Youth Engagement'), ('women', 'Women Engagement'), ('media', 'Media & Communications'), ('digital', 'Digital & Online Campaign'), ('events', 'Events & Campaign Activities'), ('other', 'Other')], default='volunteering', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Volunteer Application',
                'verbose_name_plural': 'Volunteer Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
