# Generated by Django 6.1.1 on 2026-09-11 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpowermentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('community', models.CharField(blank=True, max_length=150)),
                ('senatorial_district', models.CharField(default='Uyo Senatorial District', max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('employment_status', models.CharField(blank=True, max_length=150)),
                ('educational_background', models.CharField(blank=True, max_length=255)),
                ('reason_for_applying', models.TextField()),
                ('proposed_use', models.TextField(blank=True)),
                ('relevant_experience', models.TextField(blank=True)),
                ('expected_impact', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('waitlisted', 'Waitlisted'), ('not_selected', 'Not Selected'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empowerment Application',
                'verbose_name_plural': 'Empowerment Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmpowermentProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('programme_type', models.CharField(choices=[('skills', 'Skills Training'), ('business', 'Business Support'), ('agriculture', 'Agricultural Support'), ('education', 'Educational Support'), ('equipment', 'Equipment Support'), ('employment', 'Employment Support'), ('women', 'Women Empowerment'), ('youth', 'Youth Empowerment'), ('other', 'Other')], default='other', max_length=30)),
                ('eligibility', models.TextField(blank=True)),
                ('application_start', models.DateTimeField(blank=True, null=True)),
                ('application_end', models.DateTimeField(blank=True, null=True)),
                ('maximum_applicants', models.PositiveIntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empowerment Programme',
                'verbose_name_plural': 'Empowerment Programmes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Local Government',
                'verbose_name_plural': 'Local Governments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Official polling unit code.', max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Polling Unit',
                'verbose_name_plural': 'Polling Units',
                'ordering': ['ward', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmpowermentBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('support_received', models.CharField(max_length=255)),
                ('support_description', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_record', to='empowerment.empowermentapplication')),
            ],
            options={
                'verbose_name': 'Empowerment Beneficiary',
                'verbose_name_plural': 'Empowerment Beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='empowermentapplication',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='empowerment.empowermentprogramme'),
        ),
        migrations.CreateModel(
            name='EmpowermentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_score', models.PositiveIntegerField(default=0)),
                ('need_score', models.PositiveIntegerField(default=0)),
                ('community_impact_score', models.PositiveIntegerField(default=0)),
                ('feasibility_score', models.PositiveIntegerField(default=0)),
                ('experience_score', models.PositiveIntegerField(default=0)),
                ('constituency_balance_score', models.PositiveIntegerField(default=0)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='empowerment.empowermentapplication')),
            ],
            options={
                'verbose_name': 'Empowerment Review',
                'verbose_name_plural': 'Empowerment Reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddField(
            model_name='empowermentapplication',
            name='local_government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empowerment_applications', to='empowerment.localgovernment'),
        ),
        migrations.AddField(
            model_name='empowermentapplication',
            name='polling_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empowerment_applications', to='empowerment.pollingunit'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Official ward/registration area code.', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='empowerment.localgovernment')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['local_government', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polling_units', to='empowerment.ward'),
        ),
        migrations.AddField(
            model_name='empowermentapplication',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empowerment_applications', to='empowerment.ward'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('local_government', 'code'), name='unique_ward_code_per_lga'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('local_government', 'name'), name='unique_ward_name_per_lga'),
        ),
        migrations.AddIndex(
            model_name='empowermentapplication',
            index=models.Index(fields=['status'], name='empowerment_status_15a0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='empowermentapplication',
            index=models.Index(fields=['local_government'], name='empowerment_local_g_7c7856_idx'),
        ),
        migrations.AddIndex(
            model_name='empowermentapplication',
            index=models.Index(fields=['ward'], name='empowerment_ward_id_65b570_idx'),
        ),
        migrations.AddIndex(
            model_name='empowermentapplication',
            index=models.Index(fields=['community'], name='empowerment_communi_3937b1_idx'),
        ),
        migrations.AddIndex(
            model_name='empowermentapplication',
            index=models.Index(fields=['created_at'], name='empowerment_created_80ae99_idx'),
        ),
    ]
