# Generated by Django 6.1.1 on 2026-09-11 03:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'ordering': ['display_order', 'code'], 'verbose_name': 'Polling Unit', 'verbose_name_plural': 'Polling Units'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Ward', 'verbose_name_plural': 'Wards'},
        ),
        migrations.RemoveConstraint(
            model_name='ward',
            name='unique_ward_name_per_lga',
        ),
        migrations.RemoveField(
            model_name='localgovernment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pollingunit',
            name='address',
        ),
        migrations.AddField(
            model_name='localgovernment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localgovernment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='polling_unit_type',
            field=models.CharField(choices=[('existing', 'Existing PU'), ('new', 'New PU')], default='existing', max_length=20),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empowermentapplication',
            name='community',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='localgovernment',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_units', to='empowerment.ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ward',
            name='local_government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='empowerment.localgovernment'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='empowermentapplication',
            index=models.Index(fields=['polling_unit'], name='empowerment_polling_6dfdf8_idx'),
        ),
        migrations.RemoveField(
            model_name='ward',
            name='slug',
        ),
    ]
