# Generated by Django 6.1.1 on 2026-09-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment', '0002_alter_pollingunit_options_alter_ward_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='pollingunit',
            constraint=models.UniqueConstraint(fields=('ward', 'code'), name='unique_polling_unit_code_per_ward'),
        ),
    ]
