# Generated by Django 6.1.1 on 2026-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment', '0003_alter_pollingunit_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empowermentapplication',
            name='vin',
            field=models.CharField(blank=True, help_text='Voters Identification Number (VIN)', max_length=50),
        ),
    ]
