# Generated by Django 6.1.1 on 2026-09-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediaalbum_cover_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediavideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube, Vimeo, or external video URL.', max_length=500, null=True),
        ),
    ]
